### ISSUE TITLE
migrate to Android V2 embedding

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [mix1009/android_path_provider#6]
The plugins `android_path_provider` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by abdelaziz-mahdy** [comment]
I migrated the package 

so if anyone wants to use it u can by putting this in pubspec.yaml
```
android_path_provider:
    git:
      url: git://github.com/zezo357/android_path_provider_v2
```

hope it helped and incase there is a problem I can fix just make an issue there I will try to fix it

**Comment by steven-spiel** [comment]
@zezo357 can you create a PR for that migration?

**Comment by abdelaziz-mahdy** [comment]
@steven-spiel done but found a problem so will fix it and make a new one


edit: done

**Comment by mix1009** [comment]
Thank you all. Pull requests have been merged and published to pub.dev.
